ALTER TABLE PROJECT 
MODIFY ("NAME" VARCHAR2(4000 BYTE))
;

ALTER TABLE PROJECT_RESOURCE_ASSIGNMENT 
RENAME COLUMN "ASSIGNMTN_START_DATE" TO "ASSIGNMENT_START_DATE" ;

ALTER TABLE PROJECT_RESOURCE_ASSIGNMENT 
RENAME COLUMN "ASSIGNMTN_END_DATE" TO "ASSIGNMENT_END_DATE" ;

ALTER SEQUENCE SEQ_ISSUE 
NOMAXVALUE 
NOCACHE 
;

ALTER SEQUENCE SEQ_PROJECT 
NOMINVALUE 
NOMAXVALUE 
NOCACHE 
;

ALTER SEQUENCE SEQ_PROJ_RES_ASSIGNMENT 
NOMAXVALUE 
NOCACHE 
;

ALTER SEQUENCE SEQ_RESOURCE 
NOMAXVALUE 
NOCACHE 
;

ALTER SEQUENCE SEQ_TASK 
NOMAXVALUE 
NOCACHE 
;

