CREATE TABLE ISSUE
(
ID NUMBER NOT NULL,
TASK_ID NUMBER NOT NULL,
DESCRIPTION VARCHAR2(4000) NOT NULL,
STATUS VARCHAR2(30) NOT NULL,
LOGED_BY NUMBER NOT NULL,
ASSIGNED_TO NUMBER NOT NULL,
RESOLUTION VARCHAR2(4000)
)
;

CREATE TABLE PROJECT
(
NAME VARCHAR2(4000 BYTE) NOT NULL,
ID NUMBER NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL
)
;

CREATE TABLE PROJECT_RESOURCE_ASSIGNMENT
(
ASSIGNMNT_ID NUMBER NOT NULL,
PROJECT_ID NUMBER NOT NULL,
RESOURCE_ID NUMBER NOT NULL,
ASSIGNMTN_START_DATE DATE NOT NULL,
ASSIGNMTN_END_DATE DATE
)
;

CREATE TABLE PROJECT_TASK
(
ID NUMBER NOT NULL,
PROJECT_ID NUMBER NOT NULL,
NAME VARCHAR2(4000) NOT NULL,
STATUS VARCHAR2(30) NOT NULL,
PARENT_TASK NUMBER,
START_DATE DATE NOT NULL,
END_DATE DATE
)
;

CREATE TABLE RESOURCES
(
NAME VARCHAR2(4000) NOT NULL,
ID NUMBER NOT NULL,
USER_NAME VARCHAR2(40),
E_MAIL VARCHAR2(100),
TYPE VARCHAR2(4000)
)
;

ALTER TABLE ISSUE
ADD CONSTRAINT ISSUE_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE PROJECT
ADD CONSTRAINT PROJECT_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE PROJECT
ADD CONSTRAINT PROJECT_UK1 UNIQUE
(
NAME
)
 ENABLE
;

ALTER TABLE PROJECT_RESOURCE_ASSIGNMENT
ADD CONSTRAINT PREOJECT_RESOURCE_ASSIGNM_PK PRIMARY KEY
(
ASSIGNMNT_ID
)
 ENABLE
;

ALTER TABLE PROJECT_RESOURCE_ASSIGNMENT
ADD CONSTRAINT PREOJECT_RESOURCE_ASSIGNM_UK1 UNIQUE
(
PROJECT_ID,
RESOURCE_ID,
ASSIGNMTN_START_DATE
)
 ENABLE
;

ALTER TABLE PROJECT_TASK
ADD CONSTRAINT PROJECT_TASK_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE PROJECT_TASK
ADD CONSTRAINT PROJECT_TASK_UK1 UNIQUE
(
PROJECT_ID,
NAME
)
 ENABLE
;

ALTER TABLE RESOURCES
ADD CONSTRAINT RESOURCES_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE RESOURCES
ADD CONSTRAINT RESOURCES_NAME_UK UNIQUE
(
NAME
)
 ENABLE
;

ALTER TABLE RESOURCES
ADD CONSTRAINT RESOURCES_USER_NAME_UK UNIQUE
(
USER_NAME
)
 ENABLE
;

ALTER TABLE RESOURCES
ADD CONSTRAINT RESOURCES_EMAIL_UK UNIQUE
(
E_MAIL
)
 ENABLE
;

ALTER TABLE ISSUE
ADD CONSTRAINT ISSUE_PROJ_TASK FOREIGN KEY
(
TASK_ID
)
REFERENCES PROJECT_TASK
(
ID
) ENABLE
;

ALTER TABLE ISSUE
ADD CONSTRAINT ISSUE_LOGED_BY FOREIGN KEY
(
LOGED_BY
)
REFERENCES RESOURCES
(
ID
) ENABLE
;

ALTER TABLE ISSUE
ADD CONSTRAINT ISSUE_ASSIGNED_TO FOREIGN KEY
(
ASSIGNED_TO
)
REFERENCES RESOURCES
(
ID
) ENABLE
;

ALTER TABLE PROJECT_RESOURCE_ASSIGNMENT
ADD CONSTRAINT PREOJECT_RESOURCE_ASSIGNM_FK1 FOREIGN KEY
(
PROJECT_ID
)
REFERENCES PROJECT
(
ID
) ENABLE
;

ALTER TABLE PROJECT_RESOURCE_ASSIGNMENT
ADD CONSTRAINT PREOJECT_RESOURCE_ASSIGNM_FK2 FOREIGN KEY
(
RESOURCE_ID
)
REFERENCES RESOURCES
(
ID
) ENABLE
;

ALTER TABLE PROJECT_TASK
ADD CONSTRAINT PROJECT_TASK_PROJECT_TASK_FK1 FOREIGN KEY
(
PARENT_TASK
)
REFERENCES PROJECT_TASK
(
ID
) ENABLE
;

CREATE SEQUENCE SEQ_ISSUE INCREMENT BY 100 MINVALUE 100000 ;

CREATE SEQUENCE SEQ_PROJECT INCREMENT BY 1000 ;

CREATE SEQUENCE SEQ_PROJ_RES_ASSIGNMENT INCREMENT BY 10 MINVALUE 1000 ;

CREATE SEQUENCE SEQ_RESOURCE INCREMENT BY 1000 MINVALUE 200000 ;

CREATE SEQUENCE SEQ_TASK INCREMENT BY 100 MINVALUE 300000 ;

COMMENT ON TABLE PROJECT IS 'Project Details'
;

